### ISSUE TITLE
[📚] LLM inference API support?

### ISSUE THREAD

**Issue by yangcheng** [google/flutter-mediapipe#27]
Hi, I read about that mediapipe is supporting LLM inference, 

https://mediapipe-studio.webapps.google.com/studio/demo/llm_inference
And there are [iOS](https://github.com/googlesamples/mediapipe/tree/main/examples/llm_inference/ios) and [Android](https://github.com/googlesamples/mediapipe/tree/main/examples/llm_inference/android) examples, as well as web.

I am curious will this library support LLM inference sometime soon?

Thanks

**Comment by craiglabenz** [comment]
This was added in #26 for Android, iOS, and macOS.
